***Importing Libraries***

In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

***Uploading Iris Dataset***

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


In [5]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Iris.csv']))

***Quick Peak***

In [9]:
dataset

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [11]:
print("Shape of Dataset:",dataset.shape)

Shape of Dataset: (150, 6)


In [12]:
dataset.head(20)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa

***Statistical Summary***

In [13]:
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

***Specie Types***

In [14]:
print(dataset.groupby("Species").size())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


***Shuffling Dataset***

In [19]:
df = dataset.sample(frac = 1) 

In [20]:
df

Id  SepalLengthCm  ...  PetalWidthCm          Species
89    90            5.5  ...           1.3  Iris-versicolor
82    83            5.8  ...           1.2  Iris-versicolor
60    61            5.0  ...           1.0  Iris-versicolor
5      6            5.4  ...           0.4      Iris-setosa
149  150            5.9  ...           1.8   Iris-virginica
..   ...            ...  ...           ...              ...
130  131            7.4  ...           1.9   Iris-virginica
13    14            4.3  ...           0.1      Iris-setosa
136  137            6.3  ...           2.4   Iris-virginica
134  135            6.1  ...           1.4   Iris-virginica
53    54            5.5  ...           1.3  Iris-versicolor

[150 rows x 6 columns]

***Data Visualization : Imma Headin Out because I can do that using Tableau***

###***Creating Input and Output Variables***
So for this case, 
X is the input variable consisting values for Dimensions of Petals and Sepals, y is the output variable consisting values for the Species Name

X is Column 1 to 4
y is Column 5

In [36]:
array = df.values
X = array[:, 1:5]
y = array[:, 5]

***Splitting Dataset into Train-Test***

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

# ***Spot Check Algorithms***


K-Nearest Neighbors,
Classification and Regression Trees,
Gaussian Naive Bayes,
Support Vector Machines,
Principal Component Analysis (PCA)


1.   Logistic Regression
2.   Linear Regression


In [47]:
print("X_train Shape: ".format(X_train.shape))

X_train Shape: 


##***Linear Regression***

In [52]:
from sklearn.linear_model import LogisticRegression
linreg = LogisticRegression().fit(X_train, y_train)


***Evaluating Model and Checking Accuracy***

In [55]:
predictions = linreg.predict(X_test)

In [57]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [59]:
print(classification_report(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.82      0.90        11
 Iris-virginica       0.80      1.00      0.89         8

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30

0.9333333333333333
[[11  0  0]
 [ 0  9  2]
 [ 0  0  8]]


In [61]:
score = linreg.score(X_test, y_test)
print(score)

0.9333333333333333


***Prediction Time***

In [64]:
print(linreg.predict([[6, 3, 4, 2]]))

['Iris-versicolor']
